name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run tests (Python ${{matrix.python}}

    strategy:
      matrix:
        python:
        - "3.11"
        - "3.12"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ matrix.python }}-pip-${{ hashFiles('**/pyproject.toml') }}-git-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-python-${{ matrix.python }}-pip-${{ hashFiles('**/pyproject.toml') }}
          ${{ runner.os }}-python-${{ matrix.python }}-pip-
          ${{ runner.os }}-python-${{ matrix.python }}-
          ${{ runner.os }}-python
          ${{ runner.os }}-

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]

    - name: Run tests
      run: pytest

  all_done:
    name: Tests done
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: All done
        run: echo 1
